### ISSUE TITLE
Updating from 2.7 to 2.8

### ISSUE THREAD

**Issue by gbiagomba** [1N3/Sn1per#100]
Hello,

I had some trouble updating from 2.7 to 2.8, the update function kicked off as it should but after it got done. It kept saying it was still on version 2.7 and that 2.8 was available for updating. So I had to remove the old github file and re-download it, that is when it started working. So I got the update working but i thought i should let you know so you could maybe put the word out and give a heads up to others who might encounter this issue.

P.S Git pull in the folder doesnt work, or it didnt work, so i had to

**Comment by menzow** [comment]
Hey @gbiagomba , thanks for your report.

Do you maybe still have the output from the sniper update command and/or the gem install errors?
And which operating system are you running? Distro + version number.

Since Sn1per is basically a wrapper around a bunch of different tools, the cause of your issue(s) can be a breaking change in sn1per, one of the tools it runs on or possible one of the many dependencies that each of those tools have. Any information that helps replicating your issue will help resolving the problem 👍 

My best guess right now is that the failing ruby task from #102 is the cause of this issue. Solving that issue will probably also resolve this one.

Thanks.

**Comment by gbiagomba** [comment]
@menzow Unfortunately I do not have the original output but I am running Kali Linux 2. But thank you for getting back to me @menzow

**Comment by menzow** [comment]
Hey @gbiagomba,

A bit late for a response but are you able to reproduce this issue? I've been able to run installs and updates on a clean system. I might be able to add a fallback if I can reproduce the issue :)

**Comment by gbiagomba** [comment]
@menzow Apologies for the tardy reply, I was able to manually update to 2.8, I have checked sniper to see if there was a new version but I will check shortly and let you know if I come across anything!

**Comment by gbiagomba** [comment]
I did not get any issues with running sniper update, i can try it on another build I have to see if it works
