### ISSUE TITLE
THC Hydra Password Guessing

### ISSUE THREAD

**Issue by gbiagomba** [1N3/Sn1per#101]
Hello,

So I been using the tool to perform a few assessments at work. I noticed that THC Hydra identified that a default password was in use however when validating it with admins, the finding was incorrect. It was deemed a false positive. I did not think much of it and moved on but this kept happening on every engagement I use it on. Then I tried cross referencing using a  different tool and I got consistent conflicting results with other tools. I say all that to say that perhaps it would be better to use something else for passwork guessing. Something like medus, john the ripper, or ncrack.

**Comment by 1N3** [comment]
Hi, thanks for the heads up. This is definitely a known issue I've been meaning to find a solution to due to the way hydra handles/tests basic authentication against sites that do not have basic auth enabled. I may disable basic auth checks or use another tool but will leave this open in the meantime.

**Comment by xenonfox** [comment]
there are some bugs with ur programme its not making the dir in the form of
ntfs partition so plz re debug the code and forward it to evaluate .

**Comment by gbiagomba** [comment]
@xenonfox You should probably open a separate ticket for that request...

**Comment by gbiagomba** [comment]
@1N3 Thank you for getting back to me
