### ISSUE TITLE
huge docker Image

### ISSUE THREAD

**Issue by craig** [1N3/Sn1per#121]
The docker image is really large with its 1GB, would it be possible to build a more minimal one?

**Comment by 1N3** [comment]
I don't manage the docker images but you can open an issue here https://github.com/menzow/sn1per-docker and see if there's anything @menow can do. I think this is due to the extensive plugins required by Sn1per to run, so there may not be a great solution. I may develop a sniper "light" version that will only use core Kali tools, but that will take some time.
