### ISSUE TITLE
Metasploit intergration

### ISSUE THREAD

**Issue by gbiagomba** [1N3/Sn1per#128]
So I performed a scan using Sn1per and when it performed the metasploit nmap scan, it also used an IP i had in my default workspace in the scan. So an IP that was unrelated to this scan I was running got lumped into the metasploit scan if that makes any sense. Is there anyway to create a temp work space in metasploit to avoid this from happening?

**Comment by 1N3** [comment]
Yeah, so I think what's happening is that sniper uses whatever NMap XML files are in the workspace directory (ie. /usr/share/sniper/loot/workspace/alias/nmap) and imports all XML files into metasploit's workspace which uses the same name. Kind of confusing but essentially, metasploit must have historical scan data for that workspace alias even though the sniper scan did not go through and actively scan the host again. 

The fix is simple though. The workspace switch (sniper -w alias_name) should be new/unique if you want a fresh workspace. Otherwise, it will combine whatever is scanned into the workspace specified even if it already contains old/past scan data. This will create a new sniper workspace and also a new Metasploit workspace with the same name if that makes sense.

```sniper -w domain_alias -t target.com```

**Comment by gbiagomba** [comment]
understood, thanks again
