### ISSUE TITLE
Metasploit not running via docker

### ISSUE THREAD

**Issue by nicocolt** [1N3/Sn1per#197]
Hello,

When running Sn1per via Docker engine, Metasploit is not working:

```
[-] ***
[-] * WARNING: No database support: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Cannot assign requested address
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
```

My conf: Kali 2018.1 on virtualbox with docker-ce installed.

Let me know,
Best regards,
Nico

**Comment by cathedrall** [comment]
This is what I did which is a quick and ugly hack:
**Fix:**
Build the docker image (run in the Sn1per directory):
`sudo docker build -t sn1per-docker .`

Once built run:
`docker run -it sn1per-docker /bin/bash`
`service postgresql start`
`nano /usr/bin/msfdb`

Replace the systemctl commands in the msfdb script with the appropriate service commands.
You'll have to tweak the commands - as example:
` systemctl status postgresql` 
should be 
`service postgresql status` and so on. 

Save and issue the command 
`msfdb reinit`
test by running `msfconsole`.

Add `service postgresql start` to /usr/bin/sniper below shebang (`#!/bin/bash`) but above the beginning of the script so it's started first.

Before exiting the container, run `docker commit <container id> sn1per-docker` (<container id> obtained by running `docker ps` and look under 'CONTAINER ID')

I created a simple bash script on my local machine (not the docker container) that simply calls sniper docker which works well enough. 

`#!/bin/bash`
`docker run -it sn1per-docker sniper $@`

Save and `chmod +x sniper` 

And you should be good to go. 

*Background*:
As of Metasploit version 5.0 the msfdb script uses systemd, which inside the docker container doesn't work. I don't know the details, I just know systemd isn't working inside the container. So we changed the msfdb script to use service control instead of systemd. 

The other issue is that although the database is configured, there's no good way that I've found of making sure the database service runs on every run of the container. The simplest and fastest way was to just add it to the sniper script inside the container, commit the change and this ensures the database is started on each run of the container (i.e., sniper itself). 

This isn't ideal, mostly because I believe the results don't save anyway once sniper completes it's run, so it's a moot point I think. Feel free to correct me on this, but this I believe how it works. I'm not an expert or on containers and docker or any of that, and I just hacked this together to get it working.

**Comment by Alexis6307** [comment]
Solved with latest pull request

**Comment by 1N3** [comment]
@nicocolt Let us know if the latest docker release fixed the issue or not. Feel free to reopen.
