### ISSUE TITLE
change LHOST for metasploit

### ISSUE THREAD

**Issue by Jinovas** [1N3/Sn1per#198]
I've noticed that when running sniper in a vm, the metasploit module sets the LHOST IP to the VMware's IP instead of the external IP i get from my VPN. I saw in the sniper.conf file that there's an option to set the metasploit scanner module IP and port, however, it doesn't seem to change the LHOST IP and port for when it runs an exploit.

Reason I am testing this on a VM is because my VPN supports port forwarding and can be done easily; however, in linux since I use openvpn, it's a bit of a nightmare to set it up.

**Comment by 1N3** [comment]
Thanks for the heads up. Do you know which exploit was attempted and failed exactly? Also, have you confirmed that the exploit works manually via msfconsole if the correct LHOST/LPORT values are set?

I noticed a few exploits use the default setting for LHOST instead of the value in the sniper.conf file, so I'm working on updating those now.

**Comment by Jinovas** [comment]
I tried doing it manually and noticed a couple of the exploits didn't even have a LHOST option in msfconsole. Granted, I thought it might of been just because of the particular kind of FTP exploits I was playing with but I'm not sure atm. I will try to confirm tonight though and let you know

**Comment by Jinovas** [comment]
Update:

I took another look and it looks like I just misread the output. The LHOST was set correctly and I got that mixed up with TCP handler IP. Lol. Closing out =)
