### ISSUE TITLE
massdns super slow

### ISSUE THREAD

**Issue by dorkerdevil** [1N3/Sn1per#230]
massdns is taking really long time . . .  and is super slow

**Comment by 1N3** [comment]
I don't think there's any way around this due to the amount of domains being queried but you can selectively disable it in your ~/.sniper.conf by setting MASSDNS="0". You may also want to disable altdns and dnsgen since they rely on massdns:

ALT_DNS="0"
MASS_DNS="0"
DNSGEN="0"

That being said, if you want to really do a deep dive on the subdomains available, it might be worth the wait to find those unique/hard to find sub-domains.

**Comment by dorkerdevil** [comment]
thanks for the info



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
10/10/19,
08:33:44 AM
