### ISSUE TITLE
Script - freezes at massbleed - continue script please - error handler? 

### ISSUE THREAD

**Issue by Biedubbeljoe** [1N3/Sn1per#41]
![screenshot from 2016-08-18 14 54 44](https://cloud.githubusercontent.com/assets/15264264/17774789/95ad8198-6555-11e6-826f-955dffb50507.png)

**Comment by 1N3** [comment]
Looks like a firewall has blocked you or port 443/tcp is no longer open. In most cases, it should continue to run if the port is closed, but if the firewall blocks you mid-scan, it could cause the script to hang. Since MassBleed relies on sslscan, you could also just run 'killall sslscan' to kill it which will continue with any remaining tests. I'll see what I can do to fix this in the meantime.

**Comment by Biedubbeljoe** [comment]
Thx.

**Comment by 1N3** [comment]
no prob!

**Comment by dukeminus** [comment]
tried using killall sslscan it does nothing

**Comment by Biedubbeljoe** [comment]
if sniper stops at massbleed use the command: 
ps aux
find the PID number (first row) for the massbleed proces and use the command:
kill xxxxx
where xxxxx is the PID number, to kill the massbleed proces, and the script will keep on running..
