### ISSUE TITLE
RHOST failed

### ISSUE THREAD

**Issue by ghost** [1N3/Sn1per#67]
USER_FILE => /usr/share/brutex/wordlists/simple-users.txt
RHOSTS => 192.168.241.147
[!] RHOST is not a valid option for this module. Did you mean RHOSTS?
RHOST => 192.168.241.147

the RHOST parameter is wrong, should RHOSTS ?

**Comment by 1N3** [comment]
Hi, thanks for the feedback here. Setting RHOSTS and RHOST together should still make the exploit run, you'll just get an error if the script doesn't accept the parameter. I will look into cleaning this up though in a future release.

**Comment by menzow** [comment]
Since sniper is chaining metasploit modules it's gonna need both RHOST and RHOSTS. These verbose warnings are just modules complaining that a global parameter is being set while they're loaded.

Maybe it's a good idea sniper first sets up the exploit context and then runs the exploit chain. I just tried this locally and seems to work great. I think a simple search and replace would fix all "issues" `/msfconsole -x "/msfconsole -x"setg RHOST "$TARGET"; setg RHOSTS "$TARGET";/`

**Comment by 1N3** [comment]
Closing this out for now as Sn1per currently sets both RHOST and RHOSTS variable for metasploit. The warnings received should not affect functionality of any exploits as long as one of the variables is set correctly.
